apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: default-ns-deny-all
  namespace: default

---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default-strict-mode
  namespace: default
spec:
  mtls:
    mode: STRICT
